# Generated by Django 4.2.1 on 2023-08-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(max_length=100, unique=True)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('privilege', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
