# Generated by Django 4.2.1 on 2024-01-11 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_active_user_last_login_alter_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+0988888888'. Up to 10 digits allowed.", regex='/(84|0[3|5|7|8|9])+([0-9]{8})\\b/g')]),
        ),
    ]
