# Generated by Django 5.0.4 on 2024-07-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.category'),
        ),
    ]
