# Generated by Django 5.0.4 on 2024-07-05 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_id_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id_category',
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog')),
                ('id_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.category')),
            ],
        ),
    ]
