# Generated by Django 5.0.4 on 2024-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_blog_id_category_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='id_category',
            field=models.ManyToManyField(to='Blog.category'),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
